### ISSUE TITLE
Preferences cannot be accessed in Gnome 40

### ISSUE THREAD

**Issue by kdwk** [Darazaki/AutoDayNightThemeSwitch#5]
The extension works correctly with default parameters. Clicking on the preferences icon (both on extensions.gnome.org and in Gnome Tweaks) results in a window that says something went wrong and outputs the following:

```
Error: No property margin on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  buildPrefsWidget@/home/kdwk/.local/share/gnome-shell/extensions/adnts@n.darazaki/prefs.js:162:22
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

  This might be a Gnome problem, I have no idea
OS: Fedora 33
DE: Gnome 40.beta

**Comment by Darazaki** [comment]
After taking a look at the new API, it seems like the Gtk4 JavaScript bindings used by GNOME 40 do not include the `margin` property anymore and instead `margin-bottom`, `margin-top`, `margin-start` and `margin-end` have to be set to the same value one by one which caused this bug :/

It should be easy enough to fix but I won't be able to test it since I don't use GNOME anymore, I'll try to push a fix to both of this repository's branches ASAP

Thanks for telling me!

**Comment by Darazaki** [comment]
@kdwk could you confirm if it works?

You can run the following to install the fixed version, replacing the GNOME Extensions one:

```sh
git clone https://github.com/Darazaki/AutoDayNightThemeSwitch -b classic adnts
adnts/install.sh
```

Since it's just the preferences no GNOME Shell reloading should be necessary, just reopening the preferences should be enough

**Comment by kdwk** [comment]
No, it doesn't. This time it's another property:

```
Error: No property expand on GtkGrid

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:63:40
  buildPrefsWidget@/home/kdwk/.local/share/gnome-shell/extensions/adnts@n.darazaki/prefs.js:162:22
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Darazaki** [comment]
After doing a full diff on the documentation it seems they removed anything that could set several properties at once, it should be fixed now

@kdwk could you test the changes one last time please? (If it still doesn't work I'll just try to get a VM to work on my machine to avoid wasting your time)

**Comment by kdwk** [comment]
```
`TypeError: Gtk.HSeparator is not a constructor

Stack trace:
  buildPrefsWidget@/home/kdwk/.local/share/gnome-shell/extensions/adnts@n.darazaki/prefs.js:234:23
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

🤣

**Comment by Darazaki** [comment]
\>_>

**Comment by Darazaki** [comment]
Finally got a GNOME 40 build to work, the only thing left to fix was the use of `Gtk.HSeparator` instead of `Gtk.Separator`

Sorry for taking so much time to get things done but now everything should run fine on every GNOME version since 3.28!

Thanks again for the bug report :)

**Comment by kdwk** [comment]
Thanks so much for taking the time to fix it!
