### ISSUE TITLE
ImportError: No JS module 'adnts@n.darazaki' found in search path

### ISSUE THREAD

**Issue by ghost** [Darazaki/AutoDayNightThemeSwitch#6]
The settings of extension adnts@n.darazaki had an error:
```
ImportError: No JS module 'adnts@n.darazaki' found in search path
```

Stack trace:
```
installImporter@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:266:5
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:199:28
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Darazaki** [comment]
That error looks pretty weird… 

- What GNOME version are you using?
- Where did you install the extension from? (GNOME Extensions/master branch/classic branch/…)
- Does it only happen with Auto Day/Night Theme Switch?

**Comment by ghost** [comment]
- I'm using 3.36.8
- I installed it from GNOME Extensions
- Actually no, it seems to say something similar when I try clicking settings on almost all the other extensions.

**Comment by Darazaki** [comment]
Thanks for your answers!

This looks like a GNOME bug, I'll try to take a look at GNOME's code once I get some sleep to see if I can find anything to help you :)

I'll keep this issue open just in case I'm wrong. If you find anything, please keep me informed!

**Comment by ghost** [comment]
It seems that all my extensions disappeared I'll re-install them. I think everything has gone back to normal.

**Comment by Darazaki** [comment]
Wow it's the first time I see anything like that :/

If not already done, you should probably open an issue in the [GNOME Shell repository](https://gitlab.gnome.org/GNOME/gnome-shell) and repeat what you told me just in case they can do anything to fix that

I tried looking at the GNOME code but haven't found anything obvious that could help you sorry

I hope you wont encounter this bug ever again

EDIT: fyi, extensions installed by normal users are stored inside `~/.local/share/gnome-shell/extensions` so if anything happens again you should probably look here first
